'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { useTheme } from 'next-themes'
import { ArrowLeft, ArrowRight, Check, CircleHelp, Code2, Database, ExternalLink, Maximize2, Moon, Play, Server, Sun, Terminal, X } from 'lucide-react'
import { cn } from '@/lib/utils'

const LOGO = ({ compact = false }: { compact?: boolean }) => (
  <div className={cn('flex items-center gap-2', compact && 'scale-90 origin-left')} aria-label="GDSC Enetcom logo placeholder">
    <div className="flex size-9 items-center justify-center rounded-xl border border-dashed border-border bg-card text-xs font-bold text-muted-foreground">LOGO</div>
    <span className="text-sm font-semibold tracking-tight">GDSC Enetcom</span>
  </div>
)

const code = {
  memory: `tasks: Dict[int, Task] = {}\n_next_id: int = 1`,
  raw: `import psycopg\n\nconn = psycopg.connect("postgresql://postgres:postgres@localhost:5432/tasks_db")\ncur = conn.cursor()\ncur.execute(f"SELECT * FROM tasks WHERE title = '{title}'")  # SQL injection risk!\nrow = cur.fetchone()\ntask = {"id": row[0], "title": row[1], "done": row[2]}  # manual mapping`,
  engine: `import os\n\nfrom sqlalchemy import create_engine\nfrom sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, sessionmaker\n\nDATABASE_URL = os.getenv(\n    "DATABASE_URL",\n    "postgresql+psycopg://postgres:postgres@localhost:5432/tasks_db",\n)\n\nengine = create_engine(DATABASE_URL)\nSessionLocal = sessionmaker(bind=engine, autoflush=False)\n\n\nclass Base(DeclarativeBase):\n    pass`,
  model: `class TaskDB(Base):\n    __tablename__ = "tasks"\n\n    id: Mapped[int] = mapped_column(primary_key=True)\n    title: Mapped[str]\n    done: Mapped[bool] = mapped_column(default=False)`,
  session: `def get_db():\n    db = SessionLocal()\n    try:\n        yield db\n    finally:\n        db.close()`,
  crud: `# Create\ntask = TaskDB(title="Learn SQLAlchemy")\ndb.add(task)\ndb.commit()\ndb.refresh(task)\n\n# Read\ntask = db.get(TaskDB, task_id)\ntasks = db.scalars(select(TaskDB)).all()\ndone_tasks = db.scalars(select(TaskDB).where(TaskDB.done == True)).all()\n\n# Update\ntask = db.get(TaskDB, task_id)\ntask.done = True\ndb.commit()\n\n# Delete\ntask = db.get(TaskDB, task_id)\ndb.delete(task)\ndb.commit()`,
  after: `from sqlalchemy import select\nfrom sqlalchemy.orm import Session\nfrom db import Base, TaskDB, engine, get_db\n\nBase.metadata.create_all(bind=engine)\n\n@app.get("/tasks", response_model=List[Task])\ndef get_tasks(\n    done: Optional[bool] = Query(default=None),\n    db: Session = Depends(get_db),\n):\n    stmt = select(TaskDB).order_by(TaskDB.id)\n    if done is not None:\n        stmt = stmt.where(TaskDB.done == done)\n    return db.scalars(stmt).all()`,
}

const slides = [
  { type: 'title', kicker: 'SESSION 03', title: 'Databases & ORMs', subtitle: 'SQL vs NoSQL · SQLAlchemy · FastAPI', body: 'GDSC Enetcom · Software Engineering Department', presenter: 'Presenter: Amine' },
  { type: 'agenda', title: 'Today\'s route map', subtitle: 'From request/response to data that survives a restart.', items: ['Recap: APIs & FastAPI', 'Databases & ORMs', 'Project: from static to persistent'] },
  { type: 'divider', part: '01', title: 'Recap: APIs & FastAPI', subtitle: 'A quick reset before we give our API a memory.' },
  { type: 'content', part: '01', title: 'What is FastAPI?', subtitle: 'A modern Python web framework built around type hints.', bullets: ['Automatic validation', 'Interactive docs at /docs', 'Async support when you need it', 'Built on Starlette + Pydantic'], icon: 'api' },
  { type: 'restaurant', part: '01', title: "What's an API?", subtitle: 'A contract that lets software talk without knowing the implementation.', footer: 'In our case: a web API over HTTP, answering in JSON.' },
  { type: 'types', part: '01', title: 'Types of APIs', subtitle: 'We build REST today. The other shapes are useful context.', items: [['REST', 'Resources + HTTP methods', true], ['GraphQL', 'Client chooses fields'], ['gRPC', 'Fast binary calls'], ['WebSocket', 'Real-time, two-way'], ['SOAP', 'XML-based, mostly legacy']] },
  { type: 'cycle', part: '01', title: 'Frontend ↔ backend', subtitle: 'Every interaction is a request + a response.' },
  { type: 'live', part: '01', title: "Let's explore the code", subtitle: 'Opening the CRUD file from last session', chips: ['routes', 'Pydantic models', '/docs page', 'where data is stored'] },
  { type: 'code', part: '01', title: 'We did not have storage before', subtitle: 'Static data = no persistence.', code: code.memory, note: 'server restart  →  empty dict', accent: 'green' },
  { type: 'divider', part: '02', title: 'Databases & ORMs', subtitle: 'Zoom out: where should data live, and how should Python talk to it?' },
  { type: 'pipeline', part: '02', title: 'Why a database?', subtitle: 'A shared, durable source of truth for your backend.', items: ['Persistence', 'Concurrent access', 'Querying', 'Integrity', 'Security'] },
  { type: 'families', part: '02', title: 'Two families: SQL vs NoSQL', subtitle: 'You already know SQL, so let\'s zoom out.', left: ['Tables, rows', 'Fixed schema', 'Relationships'], right: ['Documents / key-value', 'Flexible schema', 'Graph / wide-column'] },
  { type: 'table', part: '02', title: 'SQL vs NoSQL', subtitle: 'A balanced comparison — choose for the shape of the problem.', rows: [['Data model', 'Relational tables', 'Documents, key-value, graph'], ['Schema', 'Fixed / explicit', 'Flexible / evolving'], ['Relationships', 'First-class', 'Usually application-managed'], ['Scaling', 'Vertical + replicas', 'Often horizontal-first'], ['Consistency', 'Strong transactions', 'Varies by system'], ['Examples', 'PostgreSQL · MySQL · SQLite', 'MongoDB · Redis · Cassandra']] },
  { type: 'choose', part: '02', title: 'When to choose which?', subtitle: 'Most apps start with a relational database.', left: ['E-commerce orders', 'Banking', 'ERP systems', 'Strong relationships + transactions'], right: ['Caching', 'Real-time feeds', 'Logs / events', 'Rapidly changing schemas'] },
  { type: 'postgres', part: '02', title: 'Our choice: PostgreSQL', subtitle: 'A production-ready relational database server.', bullets: ['Open source + widely used', 'ACID transactions', 'Rich data types, including JSON'], footer: 'SQLite is a local file. PostgreSQL is a server built for concurrent connections.' },
  { type: 'code', part: '02', title: 'The problem with raw SQL in Python', subtitle: 'Strings everywhere. Manual mapping. A dangerous interpolation.', code: code.raw, note: 'SQL injection risk', accent: 'blue' },
  { type: 'orm', part: '02', title: 'What is an ORM?', subtitle: 'Object-Relational Mapper: a translation layer, not magic.', mapping: [['Python class', 'TaskDB'], ['Database table', 'tasks'], ['Object', 'one row'], ['Attribute', 'one column']], footer: 'Pros: less boilerplate · safer queries · portable.  Cons: abstraction cost · learning curve.' },
  { type: 'compare', part: '02', title: 'Raw SQL vs ORM', subtitle: 'The same intent, expressed at two levels.', left: ['cur.execute("SELECT * FROM tasks WHERE id = %s", (task_id,))', 'INSERT INTO tasks (title) VALUES (...)'], right: ['db.get(TaskDB, task_id)', 'db.add(TaskDB(title="Learn SQLAlchemy"))'] },
  { type: 'pieces', part: '02', title: 'Meet SQLAlchemy', subtitle: 'We use the SQLAlchemy 2.0 style.', items: [['Engine', 'Connection'], ['Session', 'Conversation / unit of work'], ['Model', 'Declarative class']], footer: 'We will write all of this live in the project.' },
  { type: 'models', part: '02', title: 'Two kinds of “models”', subtitle: 'The API shape and the database shape have different jobs.', left: ['Pydantic schemas', 'API layer · main.py', 'Task · TaskCreate · TaskUpdate'], right: ['SQLAlchemy model', 'Database layer · db.py', 'TaskDB → tasks'], footer: 'Request → TaskCreate → TaskDB → DB  ·  DB → TaskDB → Task → JSON' },
  { type: 'divider', part: '03', title: 'Project: from static to persistent', subtitle: 'Same Task Management API. Now with a memory that lasts.' },
  { type: 'beforeafter', part: '03', title: 'The goal', subtitle: 'Restart the server and the tasks are still there.', before: 'FastAPI + in-memory dict', after: 'FastAPI + SQLAlchemy + PostgreSQL' },
  { type: 'files', part: '03', title: 'Project architecture: just two files', subtitle: 'No extra layers for this session.', files: [['main.py', 'FastAPI app, CORS, schemas, routes'], ['db.py', 'engine, session, TaskDB, get_db']] },
  { type: 'steps', part: '03', title: 'Live-coding checklist', subtitle: 'Follow the dependency chain from infrastructure to routes.', steps: ['Start PostgreSQL', 'Install SQLAlchemy + psycopg', 'Create db.py', 'Create tables from main.py', 'Add from_attributes=True', 'Delete tasks dict + _next_id', 'Rewrite each route with get_db', 'Run uvicorn and test /docs'] },
  { type: 'code', part: '03', title: 'db.py · 1/3', subtitle: 'Engine, session, and the declarative base.', code: code.engine, note: 'postgresql + psycopg  →  localhost:5432  →  tasks_db', accent: 'yellow' },
  { type: 'code', part: '03', title: 'db.py · 2/3', subtitle: 'The Python class maps to the tasks table.', code: code.model, note: 'id · title · done  /  primary key auto-increments', accent: 'yellow' },
  { type: 'code', part: '03', title: 'db.py · 3/3', subtitle: 'One session per request.', code: code.session, note: 'def get_tasks(db: Session = Depends(get_db))', accent: 'yellow' },
  { type: 'crud', part: '03', title: 'CRUD with SQLAlchemy 2.0', subtitle: 'Create · Read · Update · Delete', code: code.crud },
  { type: 'code', part: '03', title: 'main.py · route by route', subtitle: 'The database dependency replaces the in-memory dict.', code: code.after, note: 'db.get · commit() · order_by · database-generated ids', accent: 'red' },
  { type: 'test', part: '03', title: 'Test it end to end', subtitle: 'If it survives a restart, the migration worked.', steps: ['create → list', 'filter with ?done=true', 'get one → update → delete', 'restart FastAPI', 'inspect with psql'], command: 'docker exec -it tasks-pg psql -U postgres -d tasks_db -c "SELECT * FROM tasks;"' },
  { type: 'pitfalls', part: '03', title: 'Pitfalls & next steps', subtitle: 'Small habits prevent confusing bugs.', items: ['Forgetting commit()', 'Session lifecycle', 'N+1 queries', 'No ORDER BY = no guaranteed row order', 'Never hardcode credentials', 'Use migrations (Alembic), never hand-edit tables'] },
  { type: 'challenge', part: '03', title: 'Challenges / homework', subtitle: 'Extend the API without adding a framework-sized abstraction.', items: ['Add priority or created_at', 'Add Category with a foreign key', 'Add skip + limit pagination', 'Run FastAPI + PostgreSQL with docker-compose'] },
  { type: 'takeaways', title: 'Key takeaways', items: ['Databases give persistence.', 'SQL vs NoSQL is about data shape and needs.', 'ORMs map classes to tables.', 'SQLAlchemy + FastAPI + PostgreSQL = a clean, persistent backend.'] },
  { type: 'closing', title: 'Questions?', subtitle: 'Next session: coming soon', body: 'GDSC Enetcom · Software Engineering Department' },
]

function Dots() { return <div className="flex gap-1.5" aria-hidden="true">{['blue','red','yellow','green'].map((c) => <i key={c} className={cn('size-2 rounded-full', `dot-${c}`)} />)}</div> }
function CodeBlock({ value, accent = 'blue' }: { value: string; accent?: string }) { return <div className={cn('code-panel', `code-${accent}`)}><div className="flex items-center justify-between border-b border-white/10 px-4 py-2 text-[10px] uppercase tracking-[0.18em] text-white/50"><span>python</span><Terminal className="size-3" /></div><pre className="overflow-auto p-4 text-[clamp(9px,1.05vw,14px)] leading-[1.55] text-slate-100"><code>{value}</code></pre></div> }
function SectionLabel({ part }: { part?: string }) { return part ? <div className="mb-3 flex items-center gap-3 text-xs font-bold uppercase tracking-[0.2em] text-muted-foreground"><span className="accent-line" /> Part {part}</div> : null }
function Slide({ slide, index }: { slide: any; index: number }) {
  const common = <><SectionLabel part={slide.part} /><h1 className="slide-title">{slide.title}</h1>{slide.subtitle && <p className="slide-subtitle">{slide.subtitle}</p>}</>
  if (slide.type === 'title') return <div className="slide-shell title-slide"><div className="title-orb orb-blue" /><div className="title-orb orb-yellow" /><LOGO /><Dots /><div className="max-w-4xl"><div className="eyebrow">{slide.kicker}</div><h1 className="hero-title">{slide.title}</h1><p className="hero-subtitle">{slide.subtitle}</p><div className="mt-9 flex flex-wrap items-center gap-x-6 gap-y-2 text-sm text-muted-foreground"><span>{slide.presenter}</span><span className="text-border">/</span><span>{slide.body}</span></div></div><div className="bracket">&lt; / &gt;</div></div>
  if (slide.type === 'divider') return <div className={cn('slide-shell divider-slide', `part-${slide.part}`)}><Dots /><div className="divider-number">{slide.part}</div><div><div className="eyebrow">GDSC ENETCOM · SOFTWARE ENGINEERING</div><h1 className="slide-title">{slide.title}</h1><p className="slide-subtitle">{slide.subtitle}</p></div><div className="bracket">&lt; &gt;</div></div>
  if (slide.type === 'agenda') return <div className="slide-shell">{common}<div className="agenda-grid">{slide.items.map((item: string, i: number) => <div className="agenda-card" key={item}><span>0{i + 1}</span><strong>{item}</strong><ArrowRight className="size-5 text-muted-foreground" /></div>)}</div></div>
  if (slide.type === 'content') return <div className="slide-shell">{common}<div className="content-grid"><div className="big-icon"><Code2 /></div><div className="bullet-list">{slide.bullets.map((b: string) => <div key={b}><Check className="size-5 text-green" /><span>{b}</span></div>)}</div></div></div>
  if (slide.type === 'restaurant') return <div className="slide-shell">{common}<div className="restaurant"><div className="restaurant-node"><span>frontend</span><strong>customer</strong></div><div className="restaurant-arrow">request <ArrowRight /></div><div className="restaurant-node api-node"><span>API</span><strong>waiter</strong></div><div className="restaurant-arrow">response <ArrowRight /></div><div className="restaurant-node"><span>backend</span><strong>kitchen</strong></div></div><p className="callout">{slide.footer}</p></div>
  if (slide.type === 'types') return <div className="slide-shell">{common}<div className="types-row">{slide.items.map((it: any) => <div className={cn('type-card', it[2] && 'selected')} key={it[0]}><span>{it[0]}</span><p>{it[1]}</p></div>)}</div><p className="callout">FastAPI builds REST APIs, and can also do WebSockets.</p></div>
  if (slide.type === 'cycle') return <div className="slide-shell">{common}<div className="cycle"><div className="cycle-box blue-box"><span>01 · browser</span><strong>GET /tasks</strong><small>method · URL · headers · body</small></div><ArrowRight className="cycle-arrow" /><div className="cycle-box green-box"><span>02 · FastAPI</span><strong>validate → logic</strong><small>route handler + dependency</small></div><ArrowRight className="cycle-arrow" /><div className="cycle-box amber-box"><span>03 · response</span><strong>200 OK</strong><small>[{`{"id": 1, "title": "Learn FastAPI", "done": false}`} ]</small></div></div></div>
  if (slide.type === 'live') return <div className="slide-shell live-slide">{common}<div className="laptop"><div className="laptop-screen"><Terminal className="size-10 text-blue" /><span>main.py</span></div><div className="laptop-base" /></div><div className="chip-row">{slide.chips.map((c: string) => <span key={c}>{c}</span>)}</div></div>
  if (slide.type === 'code') return <div className="slide-shell">{common}<div className="code-layout"><CodeBlock value={slide.code} accent={slide.accent} /><div className="code-note"><div className="note-marker" /><span>{slide.note}</span></div></div></div>
  if (slide.type === 'pipeline') return <div className="slide-shell">{common}<div className="pipeline">{slide.items.map((x: string, i: number) => <div className="pipeline-card" key={x}><span>0{i + 1}</span><strong>{x}</strong></div>)}</div><div className="mini-architecture"><span>Client</span><ArrowRight /><span>FastAPI</span><ArrowRight /><span>Database</span></div></div>
  if (slide.type === 'families') return <div className="slide-shell">{common}<div className="family-grid"><div className="family-card family-sql"><div className="family-icon"><Database /></div><h3>SQL</h3>{slide.left.map((x: string) => <p key={x}>+ {x}</p>)}</div><div className="family-card family-nosql"><div className="family-icon"><Server /></div><h3>NoSQL</h3>{slide.right.map((x: string) => <p key={x}>+ {x}</p>)}</div></div></div>
  if (slide.type === 'table') return <div className="slide-shell">{common}<div className="compare-table"><div className="table-head"><span>Dimension</span><span>SQL</span><span>NoSQL</span></div>{slide.rows.map((r: string[]) => <div className="table-row" key={r[0]}><strong>{r[0]}</strong><span>{r[1]}</span><span>{r[2]}</span></div>)}</div></div>
  if (slide.type === 'choose') return <div className="slide-shell">{common}<div className="choice-grid"><div className="choice-card choice-sql"><h3>SQL</h3>{slide.left.map((x: string) => <p key={x}><Check />{x}</p>)}</div><div className="choice-card choice-nosql"><h3>NoSQL</h3>{slide.right.map((x: string) => <p key={x}><Check />{x}</p>)}</div></div></div>
  if (slide.type === 'postgres') return <div className="slide-shell">{common}<div className="postgres-grid"><div className="bullet-list">{slide.bullets.map((b: string) => <div key={b}><Check className="size-5 text-blue" /><span>{b}</span></div>)}</div><div className="server-diagram"><div>FastAPI</div><ArrowRight /><div className="driver">psycopg</div><ArrowRight /><div className="pg"><Database /><strong>PostgreSQL</strong><small>localhost:5432</small></div></div></div><p className="callout">{slide.footer}</p></div>
  if (slide.type === 'orm') return <div className="slide-shell">{common}<div className="mapping-grid">{slide.mapping.map((m: string[]) => <div className="mapping-row" key={m[0]}><span>{m[0]}</span><ArrowRight /><strong>{m[1]}</strong></div>)}</div><p className="callout">{slide.footer}</p></div>
  if (slide.type === 'compare') return <div className="slide-shell">{common}<div className="side-code"><div><span className="side-label">RAW SQL</span>{slide.left.map((x: string) => <code key={x}>{x}</code>)}</div><div><span className="side-label">SQLALCHEMY</span>{slide.right.map((x: string) => <code key={x}>{x}</code>)}</div></div></div>
  if (slide.type === 'pieces') return <div className="slide-shell">{common}<div className="pieces">{slide.items.map((it: string[]) => <div className="piece" key={it[0]}><div className="piece-icon"><Database /></div><strong>{it[0]}</strong><span>{it[1]}</span></div>)}</div><p className="callout">{slide.footer}</p></div>
  if (slide.type === 'models') return <div className="slide-shell">{common}<div className="models"><div className="model-card"><span className="model-tag">API LAYER · main.py</span><h3>{slide.left[0]}</h3>{slide.left.slice(1).map((x: string) => <p key={x}>{x}</p>)}</div><ArrowRight className="model-arrow" /><div className="model-card model-db"><span className="model-tag">DATABASE LAYER · db.py</span><h3>{slide.right[0]}</h3>{slide.right.slice(1).map((x: string) => <p key={x}>{x}</p>)}</div></div><p className="callout">{slide.footer}</p></div>
  if (slide.type === 'beforeafter') return <div className="slide-shell">{common}<div className="before-after"><div><span>BEFORE</span><strong>{slide.before}</strong><div className="empty-box">restart → empty</div></div><ArrowRight className="model-arrow" /><div className="after-box"><span>AFTER</span><strong>{slide.after}</strong><div className="full-box">restart → still here</div></div></div></div>
  if (slide.type === 'files') return <div className="slide-shell">{common}<div className="file-tree"><div className="tree-root">.</div>{slide.files.map((f: string[]) => <div className="file-row" key={f[0]}><Code2 /><strong>{f[0]}</strong><span>→ {f[1]}</span></div>)}</div><p className="callout">That&apos;s it. No extra layers.</p></div>
  if (slide.type === 'steps') return <div className="slide-shell">{common}<div className="step-grid">{slide.steps.map((s: string, i: number) => <div className="step-item" key={s}><span>{String(i + 1).padStart(2, '0')}</span><strong>{s}</strong></div>)}</div></div>
  if (slide.type === 'crud') return <div className="slide-shell">{common}<CodeBlock value={slide.code} accent="yellow" /></div>
  if (slide.type === 'test') return <div className="slide-shell">{common}<div className="test-layout"><div className="test-list">{slide.steps.map((s: string) => <div key={s}><Check />{s}</div>)}</div><CodeBlock value={slide.command} accent="green" /></div></div>
  if (slide.type === 'pitfalls' || slide.type === 'challenge') return <div className="slide-shell">{common}<div className="pitfall-grid">{slide.items.map((x: string, i: number) => <div className="pitfall" key={x}><span>0{i + 1}</span><strong>{x}</strong></div>)}</div></div>
  if (slide.type === 'takeaways') return <div className="slide-shell takeaways">{common}<div className="takeaway-list">{slide.items.map((x: string, i: number) => <div key={x}><span>0{i + 1}</span><strong>{x}</strong></div>)}</div></div>
  return <div className="slide-shell closing"><LOGO /><Dots /><div><div className="bracket">&lt; / &gt;</div><h1 className="hero-title">{slide.title}</h1><p className="hero-subtitle">{slide.subtitle}</p><p className="mt-8 text-sm text-muted-foreground">{slide.body}</p></div><div className="contact-placeholder">contact / socials</div></div>
}

export default function Page() {
  const [current, setCurrent] = useState(0)
  const [isFullscreen, setIsFullscreen] = useState(false)
  const { theme, setTheme } = useTheme()
  const slide = slides[current]
  const go = useCallback((delta: number) => setCurrent((i) => Math.min(slides.length - 1, Math.max(0, i + delta))), [])
  useEffect(() => { const onKey = (e: KeyboardEvent) => { if (e.key === 'ArrowRight' || e.key === ' ') { e.preventDefault(); go(1) } else if (e.key === 'ArrowLeft') { e.preventDefault(); go(-1) } else if (e.key.toLowerCase() === 't') setTheme(theme === 'dark' ? 'light' : 'dark'); else if (e.key.toLowerCase() === 'f') document.documentElement.requestFullscreen?.() }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey) }, [go, theme, setTheme])
  const progress = useMemo(() => ((current + 1) / slides.length) * 100, [current])
  return <main className={cn('deck-app', isFullscreen && 'is-fullscreen')} onDoubleClick={() => setIsFullscreen((x) => !x)}><div className="progress"><span style={{ width: `${progress}%` }} /></div><div className="topbar"><span className="deck-mark">DB / ORM <span>SESSION 03</span></span><div className="top-actions"><button className="icon-button" aria-label="Toggle theme" onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}>{theme === 'dark' ? <Sun /> : <Moon />}</button><button className="icon-button" aria-label="Fullscreen" onClick={() => document.documentElement.requestFullscreen?.()}><Maximize2 /></button></div></div><div className="stage"><AnimatePresence mode="wait"><motion.div key={current} className="slide-frame" initial={{ opacity: 0, x: 18 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -18 }} transition={{ duration: 0.24, ease: 'easeOut' }}><Slide slide={slide} index={current} /></motion.div></AnimatePresence></div><button className="nav-button nav-left" aria-label="Previous slide" onClick={() => go(-1)} disabled={current === 0}><ArrowLeft /></button><button className="nav-button nav-right" aria-label="Next slide" onClick={() => go(1)} disabled={current === slides.length - 1}><ArrowRight /></button><div className="bottombar"><span>GDSC Enetcom</span><div className="counter">{String(current + 1).padStart(2, '0')} <i>/</i> {String(slides.length).padStart(2, '0')}</div></div></main>
}

export { slides }
